const routineItems = [
    { event: "Morning Exercise", time: "06:00 AM" },
    { event: "Breakfast", time: "07:00 AM" },
    { event: "Office Work", time: "09:00 AM" },
    { event: "Coffee Break", time: "10:30 AM" },
    { event: "Team Meeting", time: "11:00 AM" },
    { event: "Lunch Break", time: "12:30 PM" },
    { event: "Project Work", time: "01:30 PM" },
    { event: "Client Call", time: "03:00 PM" },
    { event: "Coffee Break", time: "04:00 PM" },
    { event: "Wrap Up", time: "05:00 PM" },
    { event: "Evening Jog", time: "06:30 PM" },
    { event: "Dinner", time: "08:00 PM" },
    { event: "Reading", time: "09:00 PM" },
    { event: "TV Time", time: "10:00 PM" },
    { event: "Sleep", time: "11:00 PM" },
    { event: "Meditation", time: "06:30 AM" },
    { event: "Emails", time: "08:00 AM" },
    { event: "Work Session 1", time: "09:30 AM" },
    { event: "Lunch Break", time: "12:00 PM" },
    { event: "Work Session 2", time: "01:00 PM" },
    { event: "Afternoon Break", time: "02:30 PM" },
    { event: "Project Update", time: "03:30 PM" },
    { event: "Exercise", time: "05:00 PM" },
    { event: "Prepare for Next Day", time: "10:30 PM" },
    { event: "Family Time", time: "07:00 PM" },
];

module.exports = routineItems;