const routineItems = [
    { event: "Starting the day with a refreshing morning exercise routine", time: "06:00 AM" },
    { event: "Enjoying a hearty breakfast", time: "07:00 AM" },
    { event: "Morning meditation session", time: "08:00 AM" },
    { event: "Responding to important emails", time: "09:00 AM" },
    { event: "Going for a mid-morning coffee break", time: "10:30 AM" },
    { event: "Team meeting to discuss new project ideas", time: "11:00 AM" },
    { event: "Taking a relaxing lunch break", time: "12:00 PM" },
    { event: "Working on an exciting new project", time: "01:00 PM" },
    { event: "Going for an afternoon walk", time: "02:30 PM" },
    { event: "Updating the team on project progress", time: "03:30 PM" },
    { event: "Playing tennis at the local court", time: "05:00 PM" },
    { event: "Spending quality time with family", time: "07:00 PM" },
    { event: "Enjoying a delicious dinner with family", time: "08:00 PM" },
    { event: "Reading a captivating book", time: "09:00 PM" },
    { event: "Relaxing with some TV time", time: "10:00 PM" },
    { event: "Preparing for a good night's sleep", time: "11:00 PM" },
    { event: "Taking a peaceful morning walk", time: "06:30 AM" },
    { event: "Listening to a motivational podcast", time: "07:30 AM" },
    { event: "Doing some gardening", time: "10:00 AM" },
    { event: "Cooking a new recipe for lunch", time: "12:30 PM" },
    { event: "Painting or drawing for relaxation", time: "02:00 PM" },
    { event: "Playing a board game with friends", time: "04:00 PM" },
    { event: "Practicing yoga in the evening", time: "06:00 PM" },
    { event: "Watching a movie with loved ones", time: "08:30 PM" },
    { event: "Writing in a journal before bed", time: "10:30 PM" },
    { event: "Going for a quick morning jog", time: "07:00 AM" },
    { event: "Having a light snack", time: "11:00 AM" },
    { event: "Working on a creative project", time: "01:30 PM" },
    { event: "Doing some stretches", time: "02:00 PM" },
    { event: "Listening to classical music", time: "03:00 PM" },
    { event: "Taking a short nap", time: "04:30 PM" },
    { event: "Engaging in a hobby", time: "05:30 PM" },
    { event: "Attending an online class", time: "06:30 PM" },
    { event: "Cooking dinner with a friend", time: "07:30 PM" },
    { event: "Playing an instrument", time: "09:00 PM" },
    { event: "Organizing the home office", time: "10:00 AM" },
    { event: "Volunteering at a local charity", time: "11:30 AM" },
    { event: "Meeting a friend for coffee", time: "02:30 PM" },
    { event: "Doing a puzzle", time: "03:30 PM" },
    { event: "Writing a short story", time: "05:00 PM" },
    { event: "Practicing mindfulness", time: "06:00 AM" },
    { event: "Walking the dog", time: "08:00 AM" },
    { event: "Attending a virtual conference", time: "09:30 AM" },
    { event: "Exploring a new recipe", time: "11:00 AM" },
    { event: "Playing chess online", time: "12:00 PM" },
    { event: "Watching a documentary", time: "03:00 PM" },
    { event: "Taking an evening bike ride", time: "05:30 PM" },
    { event: "Catching up on news", time: "07:30 AM" },
    { event: "Having an evening tea", time: "08:00 PM" },
    { event: "Stargazing in the backyard", time: "09:30 PM" },
    { event: "Planning the next day's schedule", time: "10:00 PM" }
];

module.exports = routineItems;